version: "3.9"

services:
  dev:
    build: .
    container_name: simpleapp_dev
    ports:
      - "5001:5000"
    env_file:
      - ./env/dev.env

  uat:
    build: .
    container_name: simpleapp_uat
    ports:
      - "5002:5000"
    env_file:
      - ./env/uat.env

  staging:
    build: .
    container_name: simpleapp_staging
    ports:
      - "5003:5000"
    env_file:
      - ./env/staging.env

  prod:
    build: .
    container_name: simpleapp_prod
    ports:
      - "5004:5000"
    env_file:
      - ./env/prod.env

